### ISSUE TITLE
PROPOSAL - Offering a LTS-Kernel-only installation

### ISSUE THREAD

**Issue by claudiusraphaelpaeth** [danboid/ALEZ#19]
_After restudying my initial experiences with ALEZ and reading [issue #16 – ZFS hook failed to be added for LTS and feedback](https://github.com/danboid/ALEZ/issues/16) and then the accompanying notes in the Arch-Wiki about the [Kernel](https://wiki.archlinux.org/index.php/Kernel) …_

> There are various alternative Linux kernels available for Arch Linux in addition to the stable Linux kernel.

_… I realised that many of the issues i have had, may have roots in the by-design constantly-breaking on-a-daily-basis arch-repository (comparable to using Debian Unstable for example)._

**I propose therefore to have the option to do an LTS-Only-Installation of Arch-Linux via ALEZ.**

_Please let me know if this is possible and if so what would be an effective way to do so, e.g.:_

- What tasks are involved to have an Arch-Install LTS-only?
- Would it be viable or does it break Arch-Linux on next update-cycle?
- What do you, the authors, as regular Arch-users think about it?

**Comment by claudiusraphaelpaeth** [comment]
_To add a related QUESTION:_

- Would the offering of an LTS-only-ISO and as base for ALEZ online-install not be a more sane (in terms of reproducibilty of errors happening) way, to deliver ALEZ-arch*.iso as a reliable starting-point?

**Comment by danboid** [comment]
ALEZ currently installs Arch in very much the same way as the official Arch install guide which installs the base metapackage. The stable kernel is part of the Arch base metapackage. It is likely possible to split base up into its component packages and install them all but with linux-lts instead of linux. I have thought of doing this already, I just haven't been motivated enough to try doing it yet.

**Comment by danboid** [comment]
Fixed. ALEZ in LTS install mode now only installs the LTS kernel, not stable and LTS.
