### ISSUE TITLE
ISO install error

### ISSUE THREAD

**Issue by rawzone** [danboid/ALEZ#2]
Seems like the arch-keyring is to far out of date in the ISO so it refuses to install some packages which lead to the install script to fail.

Any chance for an updated ISO?

Thanks in advance.

**Comment by danboid** [comment]
I didn't think anyone was still using this!

I kinda gave up on ZFS under Arch (instead I use it under FreeBSD, for my home server) because the maintainer of the Arch ZFS repo never fixed kernel upgrades borking your system after a reboot; it then required a messy manual series of fixes to revive your system. I wrote to him several times but he seemed to be out of ideas and had no confidence in what I believed to be/ suggested as the fix. 

Has this issue been fixed yet? Can you do a kernel upgrade on an Arch machine with a ZFS root and expect it to come back after reboot without pain? If so, I'll be more inspired to get the iso updated but if you're in a hurry you'll have to create a new ISO yourself as I'm quite busy with having just moved house. I see the ZFS kernel upgrade fix as necessary for me to use or endorse the repo because the Arch kernel gets updated very frequently and I, like most Arch users, like to be current.

**Comment by danboid** [comment]
There are a couple of small tweaks I need to make to alez to make the commands match the Arch ZFS root install guide. I updated some of the ZFS install commands on the ArchWiki some time ago but never updated ALEZ to match, not thinking it was being used.

**Comment by rawzone** [comment]
Hi,

Well it's been quite some time since I used it last. But have some reinstalls upcoming so was just giving it a test before going ahead.

I normally also only use ZFS under FreeBSD, but would have loved my desktop to have some of the same features.

I have no clue what the state of ZFS under Arch is, but I know that some people are running Arch with ZFS root and home partitions.

If it's of no use for you you should not update the ISO for my sake - I'll try out to set up an Arch install with ZFS manually to test things out.

Thanks for your reply.

**Comment by danboid** [comment]
Hi rawzone

I've finally updated the ALEZ script and ISO to work with the updated zfs repo key.

Let me know if you try it please.

Thanks
