### ISSUE TITLE
Swap dataset by default?

### ISSUE THREAD

**Issue by ikidd** [danboid/ALEZ#35]
Would making a dataset for swap and allowing the user to define the size be a good plan or do you figure that's a user responsibility?

I've pretty much gone off the ubuntu plan and used:

`# zfs create -V 8G -b $(getconf PAGESIZE) -o compression=zle \
      -o logbias=throughput -o sync=always \
      -o primarycache=metadata -o secondarycache=none \
      -o com.sun:auto-snapshot=false zroot/swap`

`# echo /dev/zvol/zroot/swap none swap defaults 0 0 >> /etc/fstab`

`# swapon -av`

**Comment by danboid** [comment]
This is entirely up to the user. I haven't bothered with swap partitions since having 8+ GB RAM. It's not necessary in most cases (with 8+ GB RAM) and its detrimental to SSDs due to causing excessive writes.

We're kinda presuming most people wanting to experiment with ZFS will have a decent spec machine and they will have to learn how to create datasets to use ZFS effectively.
