### ISSUE TITLE
Update w/ newer kernel and newer ZFS? :)

### ISSUE THREAD

**Issue by fryfrog** [danboid/ALEZ#38]
Very soon after 0.8.0 came 0.8.1. And they're up to 5.1.15 now. Any chance of a new `.iso` w/ newer versions? :)

**Comment by johnramsden** [comment]
You don't really miss much in using an older ISO, since it will still install the latest kernel and ZFS. That said, a new release of the ISO on around a monthly basis - which is what the mainline Arch isos do - is probably ideal to keep the ISO up to date.

Triggered [new ISO release](https://github.com/danboid/ALEZ/releases/tag/archlinux-alez-2019.06.28.03.04.56)

**Comment by danboid** [comment]
Older ISOs with older ZFS releases will create pools in a slightly older format, often with less feature flags, which would be the argument for updating ISOs when new feature flags have been added. It is of course trivial to update pools after creation so its still no biggie.

**Comment by johnramsden** [comment]
That should only be an issue with the new minor release, since new features are only added with a version bump. For all of 0.8.x, you should mostly see bug fixes. I think that it's probably a good idea to update at least monthly, but alternatively we could update every time there's a new ZoL release.
