### ISSUE TITLE
I miss your updates... where'd you go?

### ISSUE THREAD

**Issue by fryfrog** [danboid/ALEZ#66]
Hey @danboid, where'd you go? I loved your ALEZ images for Arch installs w/ ZFS. I miss the updates! :)

**Comment by danboid** [comment]
I've lost a lot of motivation to work on this because I feel that both Ubuntu (especially since 20.04 introduced GRUB ZFS boot history and ZFS root installation) and Alpine both have official support for ZFS and don't rely on third party repos like Arch. There are still other reasons people would prefer Arch over Ubuntu or Alpine of course but its ZFS support is notably second rate.

**Comment by fryfrog** [comment]
Fair enough, thanks for the update! :)

**Comment by danboid** [comment]
I didn't answer your "What have I been up to?" bit.

Recently I wrote a cool (first of its kind?) script to auto rename music files using a program called songrec:

https://github.com/danboid/songrec-rename

and currently I'm working on a remake of of Atari's combat for the Uzebox console:

https://github.com/danboid/IKD

**Comment by fryfrog** [comment]
Haha, I actually stalked you on github and saw you were active on that game and was like "ahhhh" :)
